services:
  r8scp:
    image: r8scp
    container_name: r8scp
    environment:
      RUST_LOG: r8scp=trace
    ports:
      - "7620:7620"
    networks:
      - r8s-net

  r8sagt:
    image: r8sagt
    container_name: r8sagt
    privileged: true
    ports:
      - "7621"
    environment:
      NODE_PORT: 7621
      NODE_NAME: "r8sagt"
      R8S_SERVER_PORT: 7620
      R8S_SERVER_HOST: "r8scp"
      RUST_LOG: r8sagt=trace
    depends_on:
      - r8scp
    networks:
      - r8s-net

  etcd:
    image: quay.io/coreos/etcd:v3.6.1
    container_name: etcd
    command:
      - /usr/local/bin/etcd
      - --name=dev
      - --data-dir=/etcd-data
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://etcd:2379
      - --log-level=error
    ports:
      - "2379:2379"
    volumes:
      - etcd-data:/etcd-data
    networks:
      - r8s-net

#  grafana:
#    image: grafana/grafana
#    container_name: grafana
#    ports:
#      - "3000:3000"
#    volumes:
#      - grafana-storage:/var/lib/grafana
#      - ./grafana/provisioning:/etc/grafana/provisioning
#    environment:
#      - GF_INSTALL_PLUGINS=marcusolsson-json-datasource
#      - GF_SECURITY_ADMIN_USER=admin
#      - GF_SECURITY_ADMIN_PASSWORD=admin
#      - GF_LOG_MODE=console
#      - GF_LOG_LEVEL=off
#    depends_on:
#      - r8scp
#    networks:
#      - r8s-net

volumes:
  grafana-storage:
  etcd-data:

networks:
  r8s-net:
    driver: bridge
