services:
  r8s-server:
    image: r8s-server
    container_name: r8s-server
    environment:
        RUST_LOG: server=trace
    ports:
      - "7620:7620"
    networks:
      - r8s-net


  r8s-node:
    image: r8s-node
    container_name: r8s-node
    privileged: true
    ports:
      - "7621"
    environment:
        NODE_PORT: 7621
        NODE_NAME: "r8s-node"
        R8S_SERVER_PORT: 7620
        R8S_SERVER_HOST: "r8s-server"
        RUST_LOG: node=trace
    depends_on:
      - r8s-server
    networks:
      - r8s-net
  
# r8s-node-2:
#   image: r8s-node
#   container_name: r8s-node-2
#   privileged: true
#   ports:
#     - "7621"
#   environment:
#       NODE_PORT: 7621
#       NODE_NAME: "r8s-node-2"
#       R8S_SERVER_PORT: 7620
#       R8S_SERVER_HOST: "r8s-server"
#   depends_on:
#     - r8s-server
#   networks:
#     - r8s-net

  etcd:
    image: quay.io/coreos/etcd:v3.6.1
    container_name: etcd
    command:
      - /usr/local/bin/etcd
      - --name=dev
      - --data-dir=/etcd-data
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://etcd:2379
      - --log-level=error
    ports:
      - "2379:2379"
    volumes:
      - etcd-data:/etcd-data
    networks:
      - r8s-net


# grafana:
#   image: grafana/grafana
#   container_name: grafana
#   ports:
#     - "3000:3000"
#   volumes:
#     - grafana-storage:/var/lib/grafana
#     - ./grafana/provisioning:/etc/grafana/provisioning
#   environment:
#     - GF_INSTALL_PLUGINS=marcusolsson-json-datasource
#     - GF_SECURITY_ADMIN_USER=admin
#     - GF_SECURITY_ADMIN_PASSWORD=admin
#   depends_on:
#     - r8s-server
#   networks:
#     - r8s-net

volumes:
  grafana-storage:
  etcd-data: 

networks:
  r8s-net:
    driver: bridge
