version: '3.8'

services:
  r8s-server:
    image: r8s-server
    container_name: r8s-server
    ports:
      - "8080:8080"
    networks:
      - r8s-net

  r8s-node-1:
    image: r8s-node
    container_name: r8s-node-1
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - r8s-server
    networks:
      - r8s-net

  r8s-node-2:
    image: r8s-node
    container_name: r8s-node-2
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - r8s-server
    networks:
      - r8s-net

networks:
  r8s-net:
    driver: bridge

