services:
  cr8scp:
    image: cr8scp
    container_name: cr8scp
    environment:
      RUST_LOG: cr8scp=${LOG_LEVEL}
    ports:
      - "7620:7620"
    networks:
      - cr8s-net

  cr8sagt:
    image: cr8sagt
    privileged: true
    ports:
      - "7621"
    environment:
      NODE_PORT: 7621
      CR8S_SERVER_PORT: 7620
      CR8S_SERVER_HOST: "cr8scp"
      RUST_LOG: cr8sagt=trace
    depends_on:
      - cr8scp
    networks:
      - cr8s-net

  etcd:
    image: quay.io/coreos/etcd:v3.6.1
    container_name: etcd
    command:
      - /usr/local/bin/etcd
      - --name=dev
      - --data-dir=/etcd-data
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://etcd:2379
      - --log-level=error
    ports:
      - "2379:2379"
    volumes:
      - etcd-data:/etcd-data
    networks:
      - cr8s-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    profiles: ["grafana"]
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ../grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_PLUGINS_PREINSTALL=marcusolsson-json-datasource
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_LOG_MODE=console
      - GF_LOG_LEVEL=error
    depends_on:
      - cr8scp
    networks:
      - cr8s-net

volumes:
  grafana-storage:
  etcd-data:

networks:
  cr8s-net:
    driver: bridge
