name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24.0.5
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install protoc (protobuf compiler)
      run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

    - name: Compile all components
      run: make build
    
    - name: Install cargo-nextest
      run: cargo install cargo-nextest --locked

    - name: Run integration tests
      run: cargo nextest run --all-targets --all-features
